### PR TITLE
Expiration time validated

### PR DESCRIPTION
**Pull request by backenv**
## v1.2.1
  - `jwt_encode_*()` and `jwt_decode_*()` now can validate expiration time based on `duration` parameter, default `NULL` for back compatibility.
  - `jwt_decode_*()` now rise `warning("Not checking expiration time")` if `exp` not specified
  - All tests passing with `supressWarnings` when needed
  - Tests entry adapted to suggested packages with `requireNamespace()`
  - New unit tests for `validate_exp()`
  - Documentation adapted
  - `linterR` recommendations included

## NOTE
 Default `duration` value initially was fixed to 12h, but then failed on stored values, finally given the huge difference in tokens lifetime, `NULL` was used. Future versions could create a warning or a hard error if parameter is not supplied. Checking _immortal_ tokens could be accomplished with _far-future_ `duration` values on `jwt_decode_*()`.

### CODE REVIEW

**Comment by jeroen** [comment]
This PR is doing too many things, which makes it hard for me to review. Can you do one that just adds the feature you are interested in, without the styling changes? Also it is not needed to add your personal URL or qpdf to the description, not sure why you have done this.

**Comment by burgeon-env** [comment]
Hi @jeroen,

  I've added the description elements because I wasn't sure if you were still taking care of the repo, since the last PR from @jandix was unreviewed. No problem removing it. Same reason why I did the restyling, I can move this changes to a style-only PR.

 Regarding `jwt_decode_*`, probably `exp` is a little bit confusing, since it is the lifetime of the token in seconds and it is added to the `iat` value (`Sys.time`) at `jwt_encode_*`. Validation (`validate_exp` @ claim.R) ensures that:
 - `Sys.time() < claim$exp < Sys.time() + exp`

 What about changing the parameter name to one of `expiracy | lifetime | lifespan | life | durability`? Or any other that you consider adequate.

 Given that we define a default for the parameter, I would recommend setting it to `43200` (12h) by default, although back compatibility will be lost.

 I'll be waiting for your answer, best regards!

**Comment by jeroen** [comment]
Thank you for the contribution, sorry this took me long to review.

I agree that the decode functions should be checking expiration date, but I think your implementation based on duration is too complicated. I think only the generator of the token knows how long it should be valid, not the consumer. I don't think it makes sense to let the user limit a duration in the decode functions, if the token does not contain any expiration. 

Based on your suggestions I created an alternative PR that at least validates the `exp` field during decoding: https://github.com/r-lib/jose/pull/17

Perhaps we should add some better examples on how to generate a token with a given duration. For example:

```r
  duration <- 1000
  secret <- charToRaw("SuperSecret")
  claim <- jwt_claim("test", exp = Sys.time() + duration)
  jwt <- jwt_encode_hmac(claim, secret = secret)
```

**Comment by jeroen** [comment]
jose 1.2.0 is now on cran

**Pull request closed without merging**
